version: "3.8"
services:
  nginx:
    ports:
      - "3000:80"
    depends_on:
      - tech-domains-btc
  tech-domains-btc:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node server.js
